Feature tg 47 add/edit project page tincho
BaSP-m2022/franco-trackgenix-app pull request #10
Opened 2022-06-01 00:17 UTC by martinlotufo93

2022-06-01 01:19 UTC, HernanCazeneuve requested changes

2022-06-01 01:19 UTC, HernanCazeneuve commented on src/Components/Project/index.js
> +      console.log('mensaje prueba', newEmployees);
Remember to delete checkpoint console log

2022-06-01 01:19 UTC, HernanCazeneuve commented on src/Components/Project/index.js
> +      console.log(data);
Could also delete this console log

2022-06-01 01:26 UTC, AlejandroSantini submitted a review, later dismissed
Good job!

2022-06-03 13:09 UTC, HernanCazeneuve submitted a review, later dismissed

2022-06-04 22:09 UTC, HiginiaMed approved these changes

2022-06-04 22:15 UTC, franco-marini requested changes

2022-06-04 22:15 UTC, franco-marini commented on package.json
> +    "react-dropdown": "^1.10.0",
Remove this dependency we should not add new libreries

2022-06-04 23:38 UTC, Gearyandres94 approved these changes

2022-06-05 00:06 UTC, franco-marini commented on src/Components/Project/index.js
> +        setdescriptionValue(Projectfetch.data.description);
The capitalized letter at first should be only for components or classes. Please fix this also

2022-06-05 00:27 UTC, franco-marini approved these changes

2022-06-05 00:30 UTC, Gearyandres94 approved these changes
Great job!!!

2022-06-05 00:37 UTC, HiginiaMed approved these changes

2022-06-05 01:18 UTC, merged