BaSP-TG-42: Add / edit employee page
BaSP-m2022/franco-trackgenix-app pull request #11
Opened 2022-06-01 00:29 UTC by AlejandroSantini

2022-06-01 00:37 UTC, Gearyandres94 requested changes
Great work!!

2022-06-01 00:37 UTC, Gearyandres94 commented on src/Components/Employee/index.js
> +    if (
This could be deleted if you make the input fields required in the return.

2022-06-01 00:37 UTC, Gearyandres94 commented on src/Components/Employee/index.js
> +        console.log(data);
delete this console.log.

2022-06-03 02:13 UTC, Facund0Fernandez approved these changes
Everything works correctly. Well done!

2022-06-04 19:19 UTC, HiginiaMed approved these changes
Good job Ale!!

2022-06-04 20:51 UTC, merged