BaSP-TG-44: Add/Edit Super Admins
BaSP-m2022/franco-trackgenix-app pull request #12
Opened 2022-06-01 00:50 UTC by HernanCazeneuve

2022-06-02 00:12 UTC, Gearyandres94 reviewed
a little thing to improve but it looks really great.

2022-06-02 00:12 UTC, Gearyandres94 commented on src/Components/SuperAdmin/index.js
> +    if (firstName === '' || lastName === '' || email === '' || password === '') {
This could be deleted if you make the fields required in html.

2022-06-02 18:28 UTC, Gearyandres94 approved these changes
Everything looks great!! Great job!!

2022-06-02 18:32 UTC, CarVigil requested changes

2022-06-02 23:32 UTC, Gearyandres94 approved these changes
Great work!!!!

2022-06-04 13:47 UTC, CarVigil approved these changes

2022-06-04 22:01 UTC, HiginiaMed approved these changes

2022-06-04 22:04 UTC, merged