BaSP-TG-40: List tasks
BaSP-m2022/franco-trackgenix-app pull request #2
Opened 2022-05-30 16:37 UTC by Gearyandres94

2022-05-30 22:14 UTC, laura-brussa12 commented on src/Components/Tasks/index.js
> +      // console.log(responseJson.data);
Acá en la línea 15 deberías quitar este comentario

2022-05-30 22:15 UTC, laura-brussa12 commented on src/Components/Tasks/index.js
> +    console.log(idTask);
El console.log de la línea 24 de no ser necesario deberías sacarlo también

2022-05-30 22:17 UTC, laura-brussa12 commented on src/Components/Tasks/List/ListItem/Index.jsx
> +  // console.log('props', listItem);
Deberías quitar este comentario de la línea 5

2022-05-31 16:45 UTC, GuidoCerioni reviewed
I think you have to make some changes, but im not sure about it. If im wrong please let me know. Btw, nice work Andrés!

2022-05-31 16:45 UTC, GuidoCerioni commented on src/Components/Layout/index.js
> +    case '/task':
I think you souldn't change the URL, keep it '/tasks' and for the form, '/tasks/form'

2022-05-31 16:45 UTC, GuidoCerioni commented on src/Components/Task/index.jsx
> +const Form = () => {
You are not using this component on this branch i think

2022-05-31 20:51 UTC, tobiaspujol commented
I can't see the tasks list, and also can't add a task. In addition, when I refresh the website, it turns all white whit no data at all.

2022-05-31 21:37 UTC, Facund0Fernandez requested changes

2022-05-31 21:37 UTC, Facund0Fernandez commented on src/Components/Tasks/List/ListItem/Index.jsx
> +      <td>{listItem.projectId.name}</td>
Checking the branch I got the following error: 'TypeError: listItem.projectId is null' on this line

2022-05-31 23:09 UTC, Gearyandres94 commented on src/Components/Tasks/List/ListItem/Index.jsx
> +      <td>{listItem.projectId.name}</td>
this happens because someone delete the project that the task connects to it with the populate.

2022-06-02 18:23 UTC, Facund0Fernandez approved these changes
Everything works correctly. Good job Andy!

2022-06-04 18:12 UTC, merged