BaSP-TG-63: Created select dropdown
BaSP-m2022/franco-trackgenix-app pull request #21
Opened 2022-06-06 15:50 UTC by FiolAxel

![image](https://user-images.githubusercontent.com/101291320/172195804-39c21cf3-09a8-4c8a-b3f2-8ef5875ed69c.png)
To use: 

1. import SelectDropdown from '../Shared/SelectDropdown';
```
2. const options = [
    { value: 10, label: 'Select 1' },
    { value: 10, label: 'Select 2' }
  ];
3. return (
    <section className={styles.container}>
      <h2>Employees</h2>
      <div>
        <List list={list} deleteItem={deleteItem} setList={setList} />
      </div>
      <a className={styles.button} href="/employees/form">
        Add New Employee
      </a>
      <SelectDropdown options={options} />
    </section>
  );
};
```

2022-06-06 17:05 UTC, Facund0Fernandez submitted a review, later dismissed

2022-06-06 18:15 UTC, laura-brussa12 approved these changes

2022-06-06 22:47 UTC, GuidoCerioni requested changes
Hi Alex, check the comments!

2022-06-06 22:47 UTC, GuidoCerioni commented on src/Components/Shared/SelectDropdown/sd.module.css
> +  border: 1px solid #000;
Here, border color should be #373867

2022-06-06 22:47 UTC, GuidoCerioni commented on src/Components/Shared/SelectDropdown/index.js
> +        <option key={option.value} value={option.value}>
Here, keys must be unique, and values are the same in options

2022-06-07 02:04 UTC, Facund0Fernandez approved these changes

2022-06-07 02:32 UTC, laura-brussa12 approved these changes

2022-06-07 02:52 UTC, GuidoCerioni approved these changes
Nice!!!

2022-06-07 03:14 UTC, merged