BaSP-TG-59: Sidebar component and style
BaSP-m2022/franco-trackgenix-app pull request #23
Opened 2022-06-06 19:07 UTC by HernanCazeneuve

2022-06-06 20:20 UTC, Gearyandres94 requested changes
The file vscode/settings. should not be there.

2022-06-06 21:03 UTC, Gearyandres94 submitted a review, later dismissed
Great job!!!

2022-06-06 22:18 UTC, Facund0Fernandez approved these changes

2022-06-07 00:44 UTC, AlejandroSantini approved these changes
Good job!!

2022-06-07 00:44 UTC, AlejandroSantini commented on src/Components/Layout/index.js
> +            <Route exact path="/Tasks" component={Tasks} />
You could lowercase the path

2022-06-07 01:52 UTC, Facund0Fernandez submitted a review, later dismissed

2022-06-07 03:17 UTC, Gearyandres94 requested changes
Why do you delete the content of the header????

2022-06-07 03:54 UTC, GuidoCerioni reviewed
Like Andy says, please return the header and header styles. We return it, and everything works well. If you left it deleted, when you merge, there is the chance you delete the real header.

2022-06-07 13:36 UTC, merged