TG-57: Layout footer
BaSP-m2022/franco-trackgenix-app pull request #25
Opened 2022-06-06 23:16 UTC by martinlotufo93

2022-06-06 23:30 UTC, Facund0Fernandez reviewed
Remember to use camelCase in CSS styles

2022-06-06 23:36 UTC, Gearyandres94 requested changes

2022-06-06 23:36 UTC, Gearyandres94 commented on src/Components/Shared/Footer/footer.module.css
> +.greenline {
This class should be camel case.

2022-06-06 23:36 UTC, Gearyandres94 commented on src/Components/Shared/Footer/footer.module.css
> +.footertext {
This also should be camel case.

2022-06-06 23:36 UTC, Gearyandres94 commented on src/Components/Shared/Footer/footer.module.css
> +.footertext p {
this also should be camel case.

2022-06-06 23:36 UTC, Gearyandres94 commented on src/Components/Shared/Footer/footer.module.css
> +.rowlinks {
this also should be camel case.

2022-06-07 00:13 UTC, Facund0Fernandez commented on src/Components/Shared/Footer/footer.module.css
> +/*.main {
This comment should be uncommented or deleted.

2022-06-07 00:28 UTC, Facund0Fernandez approved these changes

2022-06-07 00:34 UTC, GuidoCerioni requested changes
Hey Martin, i see you added the .svg files AND then wrote them again inside you component. You should do it one way, or the other, not both. We are doing it by adding the files and then importing them. Check out [Facu PR](https://github.com/BaSP-m2022/franco-trackgenix-app/pull/19/files) and how he is using .svg

2022-06-07 00:37 UTC, GuidoCerioni commented
Also, you should change <a>'s for <Link />. You could see that also in Facu's PR

2022-06-07 00:40 UTC, Gearyandres94 requested changes
The svg should be as an icon or code, not both. Delete the files in public the component should still looking fine. And follow this to change the anchors with links: https://v5.reactrouter.com/web/api/Link

2022-06-07 00:40 UTC, Gearyandres94 commented on src/Components/Shared/Footer/index.js
> +          <a href={'#'}>
all anchors a should be replaced with router links

2022-06-07 00:40 UTC, Gearyandres94 commented on src/Components/Shared/Footer/index.js
> +            {' '}
This should be deleted.

2022-06-07 00:40 UTC, Gearyandres94 commented on src/Components/Shared/Footer/index.js
> +          <a href={'https://twitter.com/radiumrocket'}>
This should also be replaced.

2022-06-07 00:40 UTC, Gearyandres94 commented on src/Components/Shared/Footer/index.js
> +          <a href={'https://www.facebook.com/radiumrocket'}>
This should be replaced.

2022-06-07 00:40 UTC, Gearyandres94 commented on src/Components/Shared/Footer/index.js
> +          <a href={'https://www.instagram.com/radium.rocket/'}>
Replaces this too.

2022-06-07 00:40 UTC, Gearyandres94 commented on src/Components/Shared/Footer/index.js
> +          <a href={'#'}>
This too needs to be replaced with link routes.

2022-06-07 01:12 UTC, HernanCazeneuve approved these changes

2022-06-07 01:32 UTC, Gearyandres94 approved these changes
Great Job!!

2022-06-07 01:50 UTC, Facund0Fernandez approved these changes

2022-06-07 02:40 UTC, laura-brussa12 approved these changes

2022-06-07 03:09 UTC, GuidoCerioni approved these changes
Nice!!

2022-06-07 12:58 UTC, merged