BaSP-TG-67: Super Admin Form.
BaSP-m2022/franco-trackgenix-app pull request #27
Opened 2022-06-07 19:59 UTC by Gearyandres94

![Update](https://user-images.githubusercontent.com/58764074/172471387-af3e7d4f-dfc5-4c30-9af5-db1ffa71eeb8.PNG)
![Save](https://user-images.githubusercontent.com/58764074/172471392-e4da9f15-d9d9-4313-bf49-4af5be27f83e.PNG)

2022-06-07 22:31 UTC, HernanCazeneuve requested changes
Hell of a job

2022-06-08 18:29 UTC, CarVigil requested changes

2022-06-08 18:29 UTC, CarVigil commented on src/Components/SuperAdmin/index.js
> +/* eslint-disable no-unused-vars */
Remove this comment

2022-06-08 18:29 UTC, CarVigil commented on src/Components/SuperAdmin/index.js
> +          <Button text={'Return'} handler={routeChange} />
In all others forms, Return button is on the left.

2022-06-08 18:29 UTC, CarVigil commented on src/Components/Shared/Input/index.js
> +//
There's an empty comment. Should be removed.

2022-06-08 18:58 UTC, CarVigil submitted a review, later dismissed
Excellent 👌

2022-06-08 20:29 UTC, HernanCazeneuve approved these changes

2022-06-08 21:55 UTC, vadalamati approved these changes
Good job!!!

2022-06-08 22:16 UTC, HernanCazeneuve approved these changes

2022-06-08 23:48 UTC, FiolAxel approved these changes

2022-06-08 23:49 UTC, merged