BaSP-TG-71: Employees Form
BaSP-m2022/franco-trackgenix-app pull request #28
Opened 2022-06-07 22:19 UTC by HernanCazeneuve

![Captura de pantalla 2022-06-07 191556](https://user-images.githubusercontent.com/101070819/172492655-0b6056a0-bfe0-4087-8e3d-2b73e973c9f0.png)
![Captura de pantalla 2022-06-07 191649](https://user-images.githubusercontent.com/101070819/172492658-fe3408f5-a279-4097-b78a-a46b3fa3c059.png)

2022-06-07 23:59 UTC, CarVigil requested changes

2022-06-07 23:59 UTC, CarVigil commented on src/Components/Employee/index.js
>        <h3>Add admin</h3>
I think the title must be Add Employee

2022-06-07 23:59 UTC, CarVigil commented on src/Components/Employee/employee.module.css
>  .button {
This style isn't used. It could be deleted.

2022-06-08 17:14 UTC, Gearyandres94 requested changes
The error that you recieves from the validations of the backend should be a modal. If not the design is broken.
![Capture](https://user-images.githubusercontent.com/58764074/172677204-8d010088-dd2b-446b-9fa4-d2efb1063143.PNG)

2022-06-08 17:14 UTC, Gearyandres94 commented on src/Components/Employee/employee.module.css
>  a {
Do not use element selectors.

2022-06-08 17:14 UTC, Gearyandres94 commented on src/Components/Employee/index.js
> +            placeholder="Enter your IDN"
This should be DNI

2022-06-08 21:59 UTC, Gearyandres94 approved these changes
Great Job!!

2022-06-09 00:14 UTC, CarVigil approved these changes

2022-06-09 02:32 UTC, Facund0Fernandez submitted a review, later dismissed

2022-06-09 15:55 UTC, tobiaspujol approved these changes
PR ticket comment corrected!

2022-06-09 16:24 UTC, Gearyandres94 submitted a review, later dismissed
Good Job!!

2022-06-09 18:22 UTC, GuidoCerioni submitted a review, later dismissed
Nice job

2022-06-09 18:32 UTC, Gearyandres94 approved these changes

2022-06-09 19:21 UTC, CarVigil approved these changes
Perfect! 👌

2022-06-09 19:21 UTC, Gearyandres94 approved these changes

2022-06-09 19:39 UTC, Facund0Fernandez approved these changes

2022-06-09 19:40 UTC, merged