BaSP-TG-74: Project List
BaSP-m2022/franco-trackgenix-app pull request #29
Opened 2022-06-08 00:53 UTC by laura-brussa12

![image](https://user-images.githubusercontent.com/63599160/172508086-64c5f8e5-f099-4065-a323-6663c87327a9.png)

**Project List:**

- Implement the shared componet "Table"
-  Implement the shared componet "Modal"
-  Implement the shared componet "Button"
-  Implement the shared componet "Loading Screen"
- And Serch-bar

2022-06-08 16:03 UTC, AlejandroSantini commented on src/Components/Projects/index.js
> +  const deleteItem = async (_id) => {
The function does not need to be asynchronous

2022-06-08 16:14 UTC, AlejandroSantini commented on src/Components/Projects/index.js
> +      await fetch(`${process.env.REACT_APP_API_URL}/projects/${idToDelete}`, {
You should add setLoading (true), then setLoading (false)

2022-06-08 16:14 UTC, AlejandroSantini commented on src/Components/Shared/LoadingScreen/ls.module.css
> -  flex-direction: column;
What are these changes for?

2022-06-08 16:25 UTC, AlejandroSantini approved these changes
Nice job!

2022-06-08 17:37 UTC, AlejandroSantini submitted a review, later dismissed
Correct comments

2022-06-08 18:38 UTC, CarVigil requested changes
![image](https://user-images.githubusercontent.com/12973428/172691624-ede26cab-31cd-4273-8588-5f7d6a8b0e58.png)

2022-06-08 18:38 UTC, CarVigil commented on src/Components/Projects/index.js
> +        <Button link={'/projects/form'} text={'Add Form'}></Button>
Button must be on the left and the text should be "Add Project"

2022-06-08 18:38 UTC, CarVigil commented on src/Components/Projects/index.js
> +      <Search
Serach bar must be on the right

2022-06-08 22:04 UTC, CarVigil approved these changes

2022-06-09 14:23 UTC, FiolAxel commented
![image](https://user-images.githubusercontent.com/101291320/172870393-63336cc1-89be-46af-b6f2-05b0d1162018.png)
The title of projects is missing.

2022-06-09 14:36 UTC, FiolAxel approved these changes

2022-06-09 18:39 UTC, CarVigil submitted a review, later dismissed

2022-06-09 23:00 UTC, Gearyandres94 approved these changes
Great Job!!!

2022-06-09 23:05 UTC, FiolAxel approved these changes

2022-06-09 23:24 UTC, vadalamati submitted a review, later dismissed
Errors solved. Good job!!

2022-06-09 23:57 UTC, vadalamati approved these changes
Good job!

2022-06-09 23:59 UTC, AlejandroSantini reviewed
Nice job!

2022-06-09 23:59 UTC, AlejandroSantini commented on src/Components/Projects/index.js
> +      setLoading(false);
Delete this SetLoading

2022-06-10 00:00 UTC, AlejandroSantini approved these changes

2022-06-10 00:04 UTC, Gearyandres94 approved these changes

2022-06-10 00:05 UTC, merged