BaSP-TG-37: List admins page
BaSP-m2022/franco-trackgenix-app pull request #3
Opened 2022-05-30 16:47 UTC by Facund0Fernandez

2022-05-30 18:53 UTC, HiginiaMed commented on src/Components/Admins/index.js
> +  // API request to get admins
Remember to delete the comments!

2022-05-30 18:53 UTC, HiginiaMed commented on src/Components/Admins/index.js
> +  //API request to delete admins
Here delete comments to

2022-05-30 19:03 UTC, Gearyandres94 requested changes

2022-05-30 19:03 UTC, Gearyandres94 commented on src/Components/Admins/List/AdminsList.js
> +  console.log('admins list', list);
delete console.log

2022-05-30 19:03 UTC, Gearyandres94 commented on src/Components/Admins/ListItem/AdminsItem.js
> +  console.log('props', listItem);
delete this console.log too

2022-05-30 19:03 UTC, Gearyandres94 commented on src/Components/Admins/index.js
> +      console.log('data', responseJson.data);
Delete this console.log too.

2022-05-30 19:03 UTC, Gearyandres94 commented on src/Components/Admins/index.js
> +    console.log(responseJson);
This one should be deleted.

2022-05-30 21:46 UTC, GuidoCerioni approved these changes
Nice work Facu!

2022-05-31 19:47 UTC, CarVigil approved these changes
Everything works fine! Excelent 👌

2022-05-31 20:55 UTC, tobiaspujol commented
Works fine!

2022-06-02 00:09 UTC, Gearyandres94 approved these changes
Works fine!! great job!!

2022-06-02 00:16 UTC, merged