BaSP-TG-69: Task Form
BaSP-m2022/franco-trackgenix-app pull request #30
Opened 2022-06-08 00:57 UTC by Facund0Fernandez

- Delete older component.
- Implement inputs shared component.
- Implement buttons.
- Implement styles.
- Implement modal.
- Add redirect to list on form submit
![Task-Form](https://user-images.githubusercontent.com/101269061/172508706-a77ecf30-693c-498a-a82a-f99f7fa9be01.png)
.

2022-06-08 17:39 UTC, Gearyandres94 requested changes
The select works, but it doesn't show the value I selected. The select should be longer. The modal doesn't have a title and a text.  The button should say "Add new Task" or "Update Task". The error from the database should be a modal.

2022-06-08 17:39 UTC, Gearyandres94 commented on src/Components/Task/index.jsx
> +          console.log(projectNameValue);
Delete this console.log

2022-06-09 01:34 UTC, Gearyandres94 approved these changes
Great Job!!!

2022-06-09 01:59 UTC, Gearyandres94 submitted a review, later dismissed
Good Job!!!!

2022-06-09 19:55 UTC, GuidoCerioni approved these changes
Nice job!!

2022-06-09 22:15 UTC, vadalamati approved these changes
Goob job!!!!

2022-06-09 22:58 UTC, Gearyandres94 approved these changes

2022-06-09 23:07 UTC, FiolAxel approved these changes

2022-06-09 23:25 UTC, vadalamati approved these changes
Good job!!!

2022-06-09 23:31 UTC, merged