BaSP-TG-64: Admins List
BaSP-m2022/franco-trackgenix-app pull request #31
Opened 2022-06-08 01:00 UTC by GuidoCerioni

2022-06-08 15:17 UTC, AlejandroSantini reviewed
General class names like .container should be changed

2022-06-08 15:17 UTC, AlejandroSantini commented on src/Components/Admin/index.js
> +  return <section className={styles.container}>yjgjhghjjh</section>;
What is this return?

2022-06-08 15:28 UTC, AlejandroSantini commented on src/Components/Admins/index.js
> +            modalTitle="Are you sure you want to delete?"
You can add paragraph for the text in modalTitle, and in modalTitle put 'Admin Delete'

2022-06-08 16:26 UTC, AlejandroSantini commented on src/Components/Admins/index.js
> +            modalTitle="Are you sure you want to delete?"
You can add paragraph for the text in modalTitle, and in modalTitle put 'Admin Delete'

2022-06-08 16:26 UTC, AlejandroSantini approved these changes
Nice job Guido!

2022-06-08 17:43 UTC, AlejandroSantini requested changes
Correct comments

2022-06-08 23:08 UTC, GuidoCerioni commented on src/Components/Admin/index.js
> +  return <section className={styles.container}>yjgjhghjjh</section>;
Oh sorry, i made it so i can test if my edit button was working. This file will be deleted after merge.

2022-06-09 11:10 UTC, AlejandroSantini commented on src/Components/Admin/index.js
> +  return <section className={styles.container}>yjgjhghjjh</section>;
Okey

2022-06-09 19:47 UTC, AlejandroSantini approved these changes
Nice job!!

2022-06-09 20:14 UTC, Facund0Fernandez reviewed
Everything seems to work fine. It only remains to correct the breakage of the style when performing a search for something that does not exist in the Search component.

2022-06-09 22:24 UTC, Facund0Fernandez approved these changes

2022-06-10 16:22 UTC, HiginiaMed approved these changes

2022-06-10 19:46 UTC, Facund0Fernandez approved these changes

2022-06-10 19:47 UTC, HiginiaMed approved these changes

2022-06-10 19:52 UTC, AlejandroSantini approved these changes

2022-06-10 19:52 UTC, merged