BaSP-TG-70: Employees List
BaSP-m2022/franco-trackgenix-app pull request #34
Opened 2022-06-08 01:24 UTC by FiolAxel

- Delete older component.
- Implement Table.
- Implement Buttons.
- Implement Styles.
- Implement Modal.

2022-06-08 20:05 UTC, laura-brussa12 commented on src/Components/Employees/index.js
>    const deleteItem = async (_id) => {
This function should not be async

2022-06-08 20:07 UTC, laura-brussa12 commented on src/Components/Employees/index.js
> +  const column = [
Maybe you should move this to line 16 to have all const together

2022-06-08 21:57 UTC, HernanCazeneuve commented on src/Components/Employees/employees.module.css
> +.h2 {
try to use classnames  and not  element selectors.

2022-06-08 21:57 UTC, HernanCazeneuve commented on src/Components/Employees/employees.module.css
>    transition: all 0.2s ease-in-out;
button hover is defined in the shared component

2022-06-08 21:57 UTC, HernanCazeneuve commented on src/Components/Employees/employees.module.css
>  .button {
also coud delete these style that is not used and defined in the shared component

2022-06-09 00:10 UTC, HernanCazeneuve approved these changes

2022-06-09 00:51 UTC, Gearyandres94 requested changes
This is how it looks the loading screen.
![Asi se](https://user-images.githubusercontent.com/58764074/172741323-9326f072-a04d-4700-acbc-355a9ddd637e.PNG)

2022-06-09 00:52 UTC, Gearyandres94 commented
The add new Employee button also doesnt work.

2022-06-09 02:41 UTC, laura-brussa12 approved these changes

2022-06-09 14:15 UTC, Gearyandres94 submitted a review, later dismissed
Great Job!!!!

2022-06-09 15:42 UTC, HernanCazeneuve submitted a review, later dismissed

2022-06-09 17:24 UTC, Gearyandres94 submitted a review, later dismissed
Nice Job!!

2022-06-09 19:23 UTC, HiginiaMed submitted a review, later dismissed

2022-06-09 19:36 UTC, GuidoCerioni approved these changes
Good job!

2022-06-09 19:38 UTC, AlejandroSantini submitted a review, later dismissed
Good job!

2022-06-09 19:39 UTC, HernanCazeneuve approved these changes

2022-06-09 21:58 UTC, AlejandroSantini approved these changes
Exelent the styles!

2022-06-09 22:12 UTC, HiginiaMed approved these changes

2022-06-09 22:12 UTC, HiginiaMed approved these changes

2022-06-09 23:04 UTC, merged