BaSP-TG-68: Task List
BaSP-m2022/franco-trackgenix-app pull request #35
Opened 2022-06-08 02:02 UTC by AlejandroSantini

2022-06-08 20:12 UTC, laura-brussa12 commented on src/Components/Tasks/index.js
> +      console.log(responseJson.data);
Maybe you should delete this console.log

2022-06-08 20:13 UTC, laura-brussa12 commented on src/Components/Layout/layout.module.css
> +  margin-top: 6%;
Why you add this?

2022-06-08 20:15 UTC, laura-brussa12 commented on src/Components/Tasks/index.js
> +  const column = [
Maybe you should move this const to line 16 in order to have all the const together

2022-06-09 04:13 UTC, GuidoCerioni requested changes
Check comments!

2022-06-09 04:13 UTC, GuidoCerioni commented on src/Components/Tasks/index.js
> +        <Search searchQuery={searchQuery} setSearchQuery={search} placeholder="Search by name" />
Placeholder should be "Search by id"

2022-06-09 04:13 UTC, GuidoCerioni commented on src/Components/Tasks/index.js
> +      <div className={styles.btnTask}>
Search and Button 'Add Task' are disalign. You can put them in the same container
![image](https://user-images.githubusercontent.com/60760576/172762486-fd6d6116-d4b0-459d-90d0-fd61f8c84264.png)

2022-06-09 15:12 UTC, GuidoCerioni submitted a review, later dismissed
Weel done!!

2022-06-09 15:28 UTC, Gearyandres94 submitted a review, later dismissed
Great job!!

2022-06-09 15:34 UTC, HiginiaMed approved these changes
Good job Ale!!

2022-06-09 20:06 UTC, Gearyandres94 approved these changes

2022-06-09 22:05 UTC, GuidoCerioni approved these changes

2022-06-09 22:10 UTC, HiginiaMed approved these changes

2022-06-09 22:20 UTC, merged