BaSP-TG-72: Timesheet list
BaSP-m2022/franco-trackgenix-app pull request #36
Opened 2022-06-08 02:03 UTC by GuidoCerioni

2022-06-08 16:22 UTC, AlejandroSantini approved these changes
Nice job!

2022-06-08 16:22 UTC, AlejandroSantini commented on src/Components/TimeSheets/index.js
> +  async function deleteTimesheet(id) {
You should add setLoading (true), then setLoading (false)

2022-06-08 16:23 UTC, AlejandroSantini commented on src/Components/TimeSheets/index.js
> +            modalTitle="Are you sure you want to delete?"
The same as commented in the other PR

2022-06-08 16:23 UTC, AlejandroSantini commented on src/Components/TimeSheets/time-sheets.module.css
>  .container {
The same as commented in the other PR

2022-06-08 17:43 UTC, AlejandroSantini requested changes
Correct comments

2022-06-09 19:52 UTC, AlejandroSantini approved these changes
Exelent job!

2022-06-09 20:16 UTC, GuidoCerioni commented on src/Components/TimeSheets/index.js
> +    setLoading(false);
yes, it is there, but it doesnt shows correctly

2022-06-09 23:18 UTC, HernanCazeneuve commented on src/Components/TimeSheets/index.js
> +      alert('error');
use modal instead of alert

2022-06-09 23:18 UTC, HernanCazeneuve commented on src/Components/TimeSheets/index.js
> +        console.log('error', error);
try not to use console log

2022-06-10 12:24 UTC, CarVigil requested changes

2022-06-10 12:24 UTC, CarVigil commented on src/Components/TimeSheets/index.js
> +    const result = untouchedData.filter((employee) => employee._id.includes(value));
I think it's better to search by first or last name instead of id. What do you think?

2022-06-10 20:02 UTC, AlejandroSantini submitted a review, later dismissed
Good job!

2022-06-10 20:38 UTC, CarVigil approved these changes

2022-06-10 23:35 UTC, FiolAxel approved these changes

2022-06-11 17:33 UTC, HiginiaMed approved these changes

2022-06-11 17:34 UTC, AlejandroSantini approved these changes
Nice!

2022-06-11 17:36 UTC, Gearyandres94 approved these changes

2022-06-11 17:42 UTC, merged