Feature tg 73 time sheet form
BaSP-m2022/franco-trackgenix-app pull request #37
Opened 2022-06-08 02:39 UTC by martinlotufo93

Shared components added. I still have to add the css styles!

2022-06-08 14:40 UTC, AlejandroSantini commented
The name of the pr should respect the format 'BaSP-TG-X: Short description'

2022-06-09 22:40 UTC, Facund0Fernandez reviewed
The edit button of the list does not show the form.

2022-06-09 22:51 UTC, Facund0Fernandez commented on src/Components/TimeSheet/index.js
> +          <div>
A children should be added with a data message.

2022-06-10 13:06 UTC, CarVigil requested changes

2022-06-10 13:06 UTC, CarVigil commented on src/Components/TimeSheet/index.js
> +            <Button text="Accept" handler={routeChange} />
If there is an error, this button should not redirect

2022-06-10 20:49 UTC, GuidoCerioni requested changes
See comments. Also you should change the PR title to "BaSP-TG-73"

2022-06-10 20:49 UTC, GuidoCerioni commented on src/Components/TimeSheet/index.js
> +/*import { Children } from 'react';*/
Remove this comment

2022-06-10 20:49 UTC, GuidoCerioni commented on src/Components/TimeSheet/index.js
> +          <Button text="Update" handler={onSubmit} />
this button should display "update" or "add" depending of the request type you are making.
Something like <Button text={requestType === 'POST' ? 'Save Timesheet' : 'Update Timesheet'} handler={onSubmit} />

2022-06-11 10:25 UTC, AlejandroSantini commented
The branch have conflicts

2022-06-11 18:24 UTC, Gearyandres94 approved these changes

2022-06-11 18:24 UTC, GuidoCerioni approved these changes

2022-06-11 18:27 UTC, CarVigil approved these changes

2022-06-11 18:29 UTC, HiginiaMed approved these changes

2022-06-11 18:29 UTC, merged