BaSP-TG-79:  Project setup redux
BaSP-m2022/franco-trackgenix-app pull request #39
Opened 2022-06-11 22:45 UTC by AlejandroSantini

- Setup of React-redux, Redux Dev Tools and Redux-thunk
- Get employees example

2022-06-11 22:46 UTC, Facund0Fernandez approved these changes
Hard work!

2022-06-11 22:47 UTC, GuidoCerioni submitted a review, later dismissed

2022-06-11 23:35 UTC, franco-marini requested changes
Nice work guys! I just add some comments to fix little things. Also, I would like you to remove all the commented lines that are on the code.

Finally, please install the dependency `redux` just to ensure that will work on the different platforms

2022-06-11 23:35 UTC, franco-marini commented on src/components/Employees/index.js
> +  // const error = useSelector((state) => state.employees.error);
Maybe you could use this to show the user a modal saying that it was an error. What do you think?

2022-06-11 23:35 UTC, franco-marini commented on src/components/Employees/index.js
> +  }
These lines should be deleted since the idea is to use the state from redux

2022-06-11 23:35 UTC, franco-marini commented on src/redux/employees/thunks.js
> +      return response_1.data;
Could we rename this `response_1` to be something more descriptive? What do you think about naming it as `jsonResponse`?

2022-06-11 23:35 UTC, franco-marini commented on src/redux/employees/thunks.js
> +      return response_1.data;
Reviewing locally the code, I found an issue regarding this. Check that if there is an error the data of `response_1` is undefined and breaks the application. 

The response of an error is the following:
```js
{
  error: true,
  message: "Employee not found",
  data: undefined
}
```

Maybe with that information, you could add some logic. Let me know if you need help regarding this

2022-06-12 02:52 UTC, franco-marini reviewed
Just one little comment regarding the name on `ACTIONS`.

What do you think if we change it to `CONSTANTS`?  Or maybe another name

2022-06-12 04:23 UTC, AlejandroSantini commented
> Just one little comment regarding the name on `ACTIONS`.
> 
> What do you think if we change it to `CONSTANTS`?  Or maybe another name

We use CONSTANTS,  no problem 💪

2022-06-12 16:43 UTC, franco-marini approved these changes
🚀

2022-06-12 16:54 UTC, Facund0Fernandez approved these changes

2022-06-12 18:36 UTC, HernanCazeneuve approved these changes

2022-06-12 18:45 UTC, merged