BaSP-TG-82: Module of Admins
BaSP-m2022/franco-trackgenix-app pull request #40
Opened 2022-06-13 15:02 UTC by Facund0Fernandez

- Define and test the actions.
- Define and test the constants.
- Define and test the reducer.
- Define and test the thunks actions.
- Remove logic of 'getById' and pass entity to edit for redux.

2022-06-13 15:07 UTC, AlejandroSantini commented on src/redux/admins/reducer.js
> +    //DELETE-----------------------------------------------------
delete coments

2022-06-13 15:09 UTC, AlejandroSantini commented on src/redux/admins/reducer.js
> +    //ADD-----------------------------------------------------
You can delete coments

2022-06-13 15:09 UTC, GuidoCerioni requested changes
See comments!

2022-06-13 15:20 UTC, AlejandroSantini submitted a review, later dismissed
Good job!

2022-06-13 15:25 UTC, AlejandroSantini submitted a review, later dismissed

2022-06-13 15:44 UTC, franco-marini requested changes
Nice work! Please review the change I marked you and if you have any doubts regarding them we can talk

2022-06-13 15:44 UTC, franco-marini commented on src/components/Admin/index.js
> +        handleEditAdmin(admin._id, body);
Could you remove this function? Since you are using the action from the dispatch and using it only here it is not recommended to create a function for this. The same for `handleAddAdmin`

2022-06-13 15:44 UTC, franco-marini commented on src/components/Admin/index.js
> +        setIsOpen(!isOpen);
In this case, I would like to see a function called `handleOpenModal` where you can use it here and on line 62. What do you think?

Also, check that the name of the function I want you to add is called `OPEN`. Think about the logic of this function

2022-06-13 15:44 UTC, franco-marini commented on src/components/Admin/index.js
> +            handleClose={() => setIsOpen(!isOpen)}
In this case, I would like to see a function called `handleCloseModal` where you can use it here and on line 127. What do you think?

Also, check that the name of the function I want you to add is called `CLOSE`. Think about the logic of this function

2022-06-13 15:44 UTC, franco-marini commented on src/components/Admins/index.js
> +        data={searchQuery.length == 0 ? admins : filteredList}
A better way of doing this condition is:
```suggestion
        data={searchQuery.length ? filteredList : admins}
```

Because on binary, 0 means `false` and any other number > 0 is `true`

2022-06-13 15:44 UTC, franco-marini commented on src/redux/admins/reducer.js
> +      };
Could you review this case? Because what are doing here is adding a new value to the array and what we want is to update one of the values

2022-06-13 15:44 UTC, franco-marini commented on src/redux/admins/reducer.js
> +      };
This may break, review what we have done on the `initialState`

2022-06-13 15:44 UTC, franco-marini commented on src/components/Admins/index.js
> +  };
Could you add the logic of `handleCloseModal` here?

Another thing to fix is, to remove the param `admin` and directly on the `deleteAdmin` use the state `idDel`. 

And after those changes, use this logic on the button handler as the following:
```js
handler={handleDeleteAdmin}
```

2022-06-13 15:44 UTC, franco-marini commented on src/components/Admins/index.js
> +  const [idDel, setIdDel] = useState('');
What do you think if we use `adminId` instead? Because I don't think that the name of this state is well-descriptive

2022-06-13 18:05 UTC, GuidoCerioni approved these changes
Nice work. All changes i suggest are fixed

2022-06-13 18:43 UTC, Gearyandres94 submitted a review, later dismissed

2022-06-13 18:54 UTC, franco-marini requested changes
Nice fixes, just some little fix more and ready to go!

2022-06-13 18:54 UTC, franco-marini commented on src/redux/admins/reducer.js
> +      };
We should also clean the `employee` value to be the same as the `initialState`

2022-06-13 18:54 UTC, franco-marini commented on src/redux/admins/constants.js
> +export const ADD_ADMINS_ERROR = 'ADD_ADMINS_ERROR';
Could you please update the typo of the actions on the DELETE, PUT and ADD? Where the name of ADMIN should be ADMIN not ADMINS 😅

2022-06-13 18:54 UTC, franco-marini commented on src/components/Admins/index.js
> +        }}
You could use here the reference of `closeModal` because the prop is called handleClose 😅 
```suggestion
        handleClose={closeModal}
```

2022-06-13 21:50 UTC, franco-marini approved these changes
🚀

2022-06-13 21:50 UTC, Gearyandres94 approved these changes
Great job!

2022-06-13 22:54 UTC, Gearyandres94 submitted a review, later dismissed
Great job!!

2022-06-13 22:54 UTC, HernanCazeneuve approved these changes

2022-06-13 23:15 UTC, Gearyandres94 submitted a review, later dismissed

2022-06-13 23:15 UTC, HernanCazeneuve submitted a review, later dismissed

2022-06-13 23:26 UTC, FiolAxel submitted a review, later dismissed

2022-06-14 01:15 UTC, franco-marini approved these changes
🚀

2022-06-14 02:12 UTC, HernanCazeneuve submitted a review, later dismissed

2022-06-14 04:36 UTC, AlejandroSantini approved these changes
Nice job!

2022-06-14 14:00 UTC, franco-marini reviewed
One little comment and that it

2022-06-14 14:00 UTC, franco-marini commented on src/redux/admins/constants.js
> +export const CLEAR_ADMIN = 'CLEAR_ADMIN';
I think it should be CLEAR_ERROR 🤔 Wdyt?

2022-06-14 14:11 UTC, FiolAxel submitted a review, later dismissed

2022-06-14 14:25 UTC, HernanCazeneuve approved these changes

2022-06-14 14:55 UTC, GuidoCerioni approved these changes
Well done Facu

2022-06-14 17:54 UTC, merged