BaSP-TG-88: Add/Edit of Project
BaSP-m2022/franco-trackgenix-app pull request #47
Opened 2022-06-14 22:55 UTC by laura-brussa12

- Define and test the actions
- Define and test the constants 
- Define and test the reducer 
- Define and test the thunks actions

2022-06-15 00:12 UTC, franco-marini requested changes
Nice work! Just some little comments for the approved

2022-06-15 00:12 UTC, franco-marini commented on src/components/Project/index.js
> +                setIsOpen(!isOpen);
What do you think if we create 2 different functions regarding the close or open, they can be called `openModal` and `closeModal`

2022-06-15 00:12 UTC, franco-marini commented on src/components/Project/index.js
> +    setEmployeeOptions(newEmployees);
What do you think if you move this in another useEffect?

2022-06-15 00:12 UTC, franco-marini commented on src/redux/projects/thunks.js
> +      const response = await fetch(`${URL}`);
If you like this way, you could do it like this. Only in this function, because you don't need to concat anything
```suggestion
      const response = await fetch(URL);
```

2022-06-15 11:42 UTC, franco-marini requested changes
Please before pushing the code, have a little test locally just to check if everything works as expected. If you have any block or don't know how to continue, review with some of your teammates

2022-06-15 11:42 UTC, franco-marini commented on src/components/Project/index.js
> +  }, []);
Nice! But you missed something related to the hook and an if. What you can do is check the employee's list page and see what it is doing there?

2022-06-15 11:42 UTC, franco-marini commented on src/components/Project/index.js
> -      setEmployeeOptions(newEmployees);
I think that this logic it is not necessary, maybe you can set the employeesValue directly with the `project.employees`

2022-06-15 21:03 UTC, AlejandroSantini commented on src/components/Project/index.js
> +  /* useEffect(() => {
You should delete coments

2022-06-16 14:04 UTC, franco-marini approved these changes
![gif](https://c.tenor.com/CDsybQkGp_kAAAAC/thumbs-up-approve.gif)

2022-06-16 14:48 UTC, Gearyandres94 submitted a review, later dismissed
Great Job!

2022-06-17 14:03 UTC, Gearyandres94 approved these changes
Great job!!

2022-06-17 14:18 UTC, Gearyandres94 requested changes
When you introduce a rate and role wrong and  you make click in the error that shows it redirects to the projects list.

2022-06-17 15:07 UTC, Gearyandres94 requested changes
Great Job! But there is the same error as before just only redirects when you complete nothing in the form to add an employee to the project. Also check comments, send me a message if you need a hand.

2022-06-17 15:07 UTC, Gearyandres94 commented on src/components/Project/index.js
> +  const routeStay = () => {
Instead of this function. You could use directly close modal.

2022-06-17 15:07 UTC, Gearyandres94 commented on src/components/Project/index.js
>                  if (!error) {
Instead of using this error you could use an state to say when you need  to redirected.

2022-06-17 19:38 UTC, AlejandroSantini submitted a review, later dismissed
nice job!

2022-06-17 20:47 UTC, FiolAxel submitted a review, later dismissed

2022-06-18 14:51 UTC, AlejandroSantini commented on src/components/Project/index.js
> +    console.log('esto me llega', project);
delete console.log

2022-06-18 14:52 UTC, AlejandroSantini commented on src/components/Project/index.js
> +    console.log(employeeIdValue);
delete console.log

2022-06-18 16:27 UTC, Gearyandres94 requested changes
Great job! Just a little more! 
When you add something else to the input of active/inactive different from those two options it doesn't show an error and the modal says "project created".

2022-06-18 16:31 UTC, laura-brussa12 commented
> Great job! Just a little more! When you add something else to the input of active/inactive different from those two options it doesn't show an error and the modal says "project created".

This is another validation error that I was told yesterday that we are gonna solve this week

2022-06-18 16:39 UTC, Gearyandres94 submitted a review, later dismissed
Great Job!!

2022-06-18 18:23 UTC, AlejandroSantini approved these changes
Good job!

2022-06-18 22:46 UTC, Gearyandres94 approved these changes

2022-06-19 00:58 UTC, GuidoCerioni approved these changes
Nice work. Remember things to change this week!

2022-06-19 01:02 UTC, HiginiaMed approved these changes

2022-06-19 01:20 UTC, merged