BaSP-TG-87: Add/edit timesheets
BaSP-m2022/franco-trackgenix-app pull request #48
Opened 2022-06-15 01:54 UTC by AlejandroSantini

2022-06-15 11:54 UTC, franco-marini requested changes
Magnificient work! Just some little comments regarding the dropdowns

2022-06-15 11:54 UTC, franco-marini commented on src/components/TimeSheet/index.js
>    }, []);
Nice catch-up! But there are some cases where you won't have any information regarding the employees or the tasks.

What do you think to use some of the thunks that were created before? 

Also, could you separate this into 2 different useEffect?

2022-06-15 11:54 UTC, franco-marini commented on src/components/TimeSheet/index.js
> +    let path = `/time-sheets`;
If you don't change/modify/update the variable, you must use always `const`

2022-06-15 19:34 UTC, Facund0Fernandez commented on src/components/TimeSheet/index.js
> +      <h3 className={styles.h3}>{requestType === 'PUT' ? 'Update Admin' : 'Add Admin'}</h3>
This should not be update/add admin.

2022-06-16 02:43 UTC, Facund0Fernandez submitted a review, later dismissed

2022-06-17 21:03 UTC, FiolAxel submitted a review, later dismissed

2022-06-17 21:23 UTC, Facund0Fernandez submitted a review, later dismissed

2022-06-18 16:32 UTC, franco-marini submitted a review, later dismissed

2022-06-18 16:41 UTC, Gearyandres94 submitted a review, later dismissed

2022-06-18 18:20 UTC, Gearyandres94 approved these changes

2022-06-18 18:53 UTC, Facund0Fernandez approved these changes

2022-06-18 21:55 UTC, HiginiaMed approved these changes

2022-06-19 01:00 UTC, merged