BaSP-TG-111: Employee-Signup
BaSP-m2022/franco-trackgenix-app pull request #52
Opened 2022-06-21 20:18 UTC by HernanCazeneuve

2022-06-23 02:34 UTC, GuidoCerioni requested changes
Nice work Hernán, just see the comments

2022-06-23 02:34 UTC, GuidoCerioni commented on .vscode/settings.json
> -{
Why did you delete this file?

2022-06-23 02:34 UTC, GuidoCerioni commented on src/components/Layout/index.js
> +            <Route exact path="/employees/signup" component={EmployeeSignUp} />
path should be /employee/signup

2022-06-23 15:24 UTC, GuidoCerioni commented on src/components/Layout/index.js
> +            <Route exact path="/employees/signup" component={EmployeeSignUp} />
yes, we should use employee now

2022-06-23 16:06 UTC, CarVigil approved these changes

2022-06-24 15:36 UTC, tobiaspujol approved these changes

2022-06-24 15:38 UTC, merged