TG-103: update admin form with validations
BaSP-m2022/franco-trackgenix-app pull request #53
Opened 2022-06-21 20:59 UTC by laura-brussa12

- Add library and setup inputs
- Create validations following BE with JOI 
- Capitalize values before sending data to BE 
- Update relative routes 
- Test features

2022-06-24 01:56 UTC, GuidoCerioni requested changes
See comment!

2022-06-24 01:56 UTC, GuidoCerioni commented on src/components/Admin/index.js
> +    mode: 'onChange',
you should use default mode (onSubmit)

2022-06-24 20:51 UTC, Facund0Fernandez approved these changes

2022-06-24 21:02 UTC, FiolAxel submitted a review, later dismissed

2022-06-24 22:47 UTC, GuidoCerioni submitted a review, later dismissed
Nice job Lau!

2022-06-25 16:10 UTC, HernanCazeneuve approved these changes

2022-06-25 16:36 UTC, GuidoCerioni approved these changes
Nice work!

2022-06-25 19:07 UTC, GuidoCerioni approved these changes

2022-06-25 19:11 UTC, HernanCazeneuve approved these changes

2022-06-25 19:12 UTC, Gearyandres94 approved these changes

2022-06-25 19:12 UTC, merged

2022-06-25 20:35 UTC, GuidoCerioni commented
Hi Lau, i merged your PR after it passes testing, but with a change in utils/formatters. It solves a conflict in all others PRs caused by my merged PR. Hope you don't mind.