BaSP-TG-106: Update Super-Admin form
BaSP-m2022/franco-trackgenix-app pull request #54
Opened 2022-06-21 21:05 UTC by FiolAxel

1. Add library and setup inputs.
2. Create validations following BE with JOI.
3. Capitalize values before sending data to BE.
4. Update relative routes to be absolute.
5. Test features.

2022-06-22 17:33 UTC, Gearyandres94 requested changes
Great job! Just some little changes.

2022-06-22 17:33 UTC, Gearyandres94 commented on src/components/SuperAdmin/index.js
>  import { postSuperAdmin, putSuperAdmin } from '../../redux/superAdmins/thunks';
This "../../" in the route should be eliminated.

2022-06-22 17:33 UTC, Gearyandres94 commented on src/components/SuperAdmin/index.js
>  import { clearError } from '../../redux/superAdmins/actions';
Same as the first comment.

2022-06-22 17:33 UTC, Gearyandres94 commented on src/components/SuperAdmin/index.js
> +    mode: 'onChange',
This could be erased, because in the default mode (That is mode: 'On submit') after the form tries to submit, and there is an error the form runs in this mod.

2022-06-22 17:33 UTC, Gearyandres94 commented on src/components/SuperAdmin/index.js
>    }, [error]);
This should be changed to superAdmin.

2022-06-23 17:44 UTC, Gearyandres94 submitted a review, later dismissed
Great job!!!

2022-06-24 02:42 UTC, GuidoCerioni requested changes

2022-06-24 02:42 UTC, GuidoCerioni commented on src/components/SuperAdmin/index.js
> +const schema = Joi.object({
you missed some validations, check the [super admin validations](https://github.com/BaSP-m2022/franco-trackgenix-server/blob/master/src/validations/super-admins.js) in the server and copy those

2022-06-24 02:42 UTC, GuidoCerioni commented on src/components/SuperAdmin/index.js
> +                type="email"
if you use type=email, you get the html native error and not the text error message from joi on the email input. i think you should use type=text like the other inputs

2022-06-25 22:38 UTC, Gearyandres94 approved these changes

2022-06-25 22:40 UTC, GuidoCerioni approved these changes
Well done!! 🚀

2022-06-27 14:42 UTC, Gearyandres94 approved these changes
:rocket:

2022-06-27 15:52 UTC, laura-brussa12 approved these changes

2022-06-27 16:03 UTC, HiginiaMed approved these changes

2022-06-27 16:32 UTC, merged