BaSP-TG-107: Update tasks form
BaSP-m2022/franco-trackgenix-app pull request #57
Opened 2022-06-21 23:04 UTC by AlejandroSantini

2022-06-22 17:05 UTC, Gearyandres94 requested changes
Great job, just some little things.

2022-06-22 20:11 UTC, Gearyandres94 approved these changes

2022-06-24 01:40 UTC, GuidoCerioni approved these changes
🚀

2022-06-26 14:33 UTC, Gearyandres94 requested changes

2022-06-26 14:33 UTC, Gearyandres94 commented on src/components/Task/index.js
> +    date: Joi.date().min(Date()).required()
This doesnt work when i choose today as date.

2022-06-26 14:36 UTC, Gearyandres94 commented on src/components/Task/index.js
> +    date: Joi.date().min(Date()).required()
![Capture](https://user-images.githubusercontent.com/58764074/175819473-387caf9e-09dc-4ea9-9cce-cddc405195e1.PNG)

2022-06-26 15:03 UTC, Gearyandres94 commented on src/components/Task/index.js
> +    date: Joi.date().min(Date()).required()
Use this instead 
    date: Joi.date().greater(Date.now() - 24 * 60 * 60 * 1000).required(),

2022-06-26 16:21 UTC, Gearyandres94 submitted a review, later dismissed
:rocket:

2022-06-27 17:16 UTC, GuidoCerioni approved these changes

2022-06-27 21:37 UTC, Gearyandres94 approved these changes

2022-06-27 21:51 UTC, GuidoCerioni approved these changes

2022-06-27 23:46 UTC, HiginiaMed approved these changes

2022-06-28 00:11 UTC, merged