BaSP-TG-105: Time-Sheet form updated
BaSP-m2022/franco-trackgenix-app pull request #58
Opened 2022-06-22 00:40 UTC by martinlotufo93

The only problem that seems to be solved is the validation of the status when hitting the database.

2022-06-24 05:27 UTC, GuidoCerioni requested changes
Nice job Martin!! Please check this two little things

2022-06-24 05:27 UTC, GuidoCerioni commented on src/components/TimeSheet/index.js
> +/* eslint-disable no-unused-vars */
you shouldn't desactivate rules, try to correct your eslint errors

2022-06-24 05:27 UTC, GuidoCerioni commented on src/components/TimeSheet/index.js
>        <h3>{requestType === 'PUT' ? 'Update Time Sheet' : 'Add Time Sheet'}</h3>
i think this h3 should have  color: #373867

2022-06-24 19:43 UTC, AlejandroSantini submitted a review, later dismissed
Good job 👌

2022-06-26 15:41 UTC, Gearyandres94 requested changes
Good job! A little thing to correct.

2022-06-26 15:41 UTC, Gearyandres94 commented on src/components/TimeSheet/form.module.css
> +h3 {
This should be a class something like .h3tittle or something like that.

2022-06-27 17:17 UTC, GuidoCerioni approved these changes

2022-06-28 14:39 UTC, tobiaspujol approved these changes
changes suggested are corrected properly!

2022-06-28 14:43 UTC, merged