BaSP-TG-110: Employee Profile
BaSP-m2022/franco-trackgenix-app pull request #59
Opened 2022-06-22 02:33 UTC by GuidoCerioni

Added Profile component. It allows see his profile and update his data.

2022-06-22 16:58 UTC, Gearyandres94 requested changes

2022-06-22 19:20 UTC, Gearyandres94 approved these changes
Great job!!

2022-06-23 14:44 UTC, Gearyandres94 requested changes
Great job! You just need to delete a line of code.

2022-06-23 14:44 UTC, Gearyandres94 commented on src/components/Shared/Profile/index.js
> +      console.log('asdasd');
delete this console log

2022-06-23 15:26 UTC, Gearyandres94 approved these changes
Great job!!!

2022-06-23 15:51 UTC, HernanCazeneuve submitted a review, later dismissed

2022-06-24 14:55 UTC, Gearyandres94 submitted a review, later dismissed
Good job!!

2022-06-24 21:52 UTC, HernanCazeneuve approved these changes
great job

2022-06-25 10:55 UTC, Gearyandres94 approved these changes
Good job!

2022-06-25 16:07 UTC, HernanCazeneuve approved these changes

2022-06-25 17:04 UTC, CarVigil approved these changes

2022-06-25 18:46 UTC, merged