BaSP-TG-41: List timesheets page
BaSP-m2022/franco-trackgenix-app pull request #6
Opened 2022-05-31 13:03 UTC by AlejandroSantini

2022-05-31 16:25 UTC, GuidoCerioni requested changes
You should delete console.logs

2022-05-31 16:25 UTC, GuidoCerioni commented on src/Components/TimeSheets/List/TimeSheetsList.jsx
> +  console.log('array list', list);
Delete console.log

2022-05-31 16:25 UTC, GuidoCerioni commented on src/Components/TimeSheets/ListItem/ItemTimeSheets.jsx
> +  console.log('Time sheets list', listItem);
Delete console.log

2022-05-31 19:45 UTC, HiginiaMed approved these changes
Good job!

2022-06-02 04:30 UTC, AlejandroSantini commented on src/Components/TimeSheets/index.js
> +  // API request to delete admins
Comments are from an old commit

2022-06-02 18:05 UTC, GuidoCerioni approved these changes
Nice job!

2022-06-02 18:33 UTC, Gearyandres94 approved these changes
Looks Great!!

2022-06-02 18:33 UTC, Facund0Fernandez reviewed
The edit button redirects home. This is correct?

2022-06-02 18:45 UTC, Facund0Fernandez approved these changes

2022-06-03 00:07 UTC, AlejandroSantini commented
> The edit button redirects home. This is correct?

The edit button redirects to <a href={`/time-theets/form?id=${listItem._id}`}>{pencil}</a>, I hope I understood your comment well.

2022-06-04 20:51 UTC, merged