BaSP-TG-125: Integrated Signup
BaSP-m2022/franco-trackgenix-app pull request #68
Opened 2022-06-29 00:44 UTC by FiolAxel

Work on the employee redux and thunks folders for the integration of the form with the server.

2022-06-30 15:38 UTC, Gearyandres94 requested changes

2022-06-30 15:38 UTC, Gearyandres94 commented on src/redux/employees/reducer.js
> +  loggedEmployee: {}
This logged employee will no grab it from the token?

2022-07-01 16:28 UTC, Gearyandres94 approved these changes
🚀

2022-07-01 16:58 UTC, GuidoCerioni submitted a review, later dismissed

2022-07-01 17:21 UTC, GuidoCerioni approved these changes

2022-07-01 17:21 UTC, Gearyandres94 approved these changes

2022-07-01 23:05 UTC, HiginiaMed approved these changes

2022-07-01 23:05 UTC, merged