TG-142: Landing Page
BaSP-m2022/franco-trackgenix-app pull request #79
Opened 2022-07-18 16:00 UTC by FiolAxel

Created the landing page with JSX and CSS

2022-07-25 18:47 UTC, Gearyandres94 requested changes

2022-07-25 18:47 UTC, Gearyandres94 commented on src/components/Shared/Input/index.js
> +function Input({ label = '', name, type, value, placeholder, error, onChange, min, max }) {
Why do you add this props??

2022-07-25 18:47 UTC, Gearyandres94 commented on src/components/Shared/Input/index.js
> +function Input({ label = '', name, type, value, placeholder, error, onChange, min, max }) {
Why do you add this props??

2022-07-25 20:25 UTC, Gearyandres94 approved these changes
🚀

2022-07-26 19:16 UTC, Gearyandres94 approved these changes

2022-07-26 19:27 UTC, vadalamati approved these changes
Goob job!

2022-07-26 19:29 UTC, GuidoCerioni approved these changes

2022-07-26 19:29 UTC, merged