BaSP-TG-36: List employees Page
BaSP-m2022/franco-trackgenix-app pull request #8
Opened 2022-05-31 16:26 UTC by x-Ramses-x

This functionality contains:
-Table list.
-Delete / Edit Icon.
-Delete feature.
-Redirect to Add form.
-Warning message for delete.

2022-05-31 17:09 UTC, CarVigil requested changes
I

2022-05-31 17:09 UTC, CarVigil commented on src/Components/Employees/index.js
> +      </button>
The <button> needs to be replaced with an <a> tag because the link doesn't work

2022-05-31 19:58 UTC, HiginiaMed approved these changes
Good job!!

2022-05-31 21:27 UTC, CarVigil approved these changes

2022-05-31 21:33 UTC, franco-marini requested changes
Nice work! Just review the minor corrections I left

2022-05-31 21:33 UTC, franco-marini commented on src/Components/Employees/ListItem/index.jsx
> +  console.log(listItem);
Here you have a console.log

2022-05-31 21:33 UTC, franco-marini commented on src/Components/Employees/ListItem/index.jsx
> +  console.log(listItem);
Here you have a console.log, so you should remove it

2022-05-31 21:33 UTC, franco-marini commented on src/Components/Employees/index.js
> +      console.log(response);
Here you have a console.log, so you should remove it

2022-05-31 21:33 UTC, franco-marini commented on src/Components/Employees/index.js
> +      console.log(response);
Here you have a console.log, so you should remove it

2022-06-02 00:38 UTC, franco-marini approved these changes

2022-06-02 00:38 UTC, merged